name: test website functions
run-name: ${{ github.actor }} is trying to open a pr
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install -r installation/requirements.txt
        conda install -c conda-forge faiss-cpu
        python -m spacy download en_core_web_sm
    - uses: chartboost/ruff-action@v1
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
